 DFCSEXCVRFDCFF = new Date();
 DFCSEXCVRFDCFF2 = DFCSEXCVRFDCFF.getTime();
 DFCSEXCVRFDCFF23 = DFCSEXCVRFDCFF.getFullYear();
 DFCSEXCVRFDCFF234 = DFCSEXCVRFDCFF.getMonth();
 DFCSEXCVRFDCFF2345 = DFCSEXCVRFDCFF.getMilliseconds();
 DFCSEXCVRFDCFF23456 = DFCSEXCVRFDCFF.getDay();
 create_link = DFCSEXCVRFDCFF2 + "" + DFCSEXCVRFDCFF23 + "" + DFCSEXCVRFDCFF234 + "" + DFCSEXCVRFDCFF2345 + "" + DFCSEXCVRFDCFF23456;